EnterpriseResourcePlanning/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

from EnterpriseResourcePlanning import views, settings

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^update/', include('Update.urls')),
    url(r'^register/', include('Registration.urls')),
    url(r'^attendance/', include('Attendance.urls')),
    # url(r'^administrator/', include('administrator.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^login/', include('Login.urls')),
    url(r'^dashboard/', include('Dashboard.urls')),
    url(r'^timetable/', include('Timetable.urls')),
    url(r'^request/', include('Requests.urls')),
    url(r'^report/', include('Report.urls')),
    url(r'^general/', include('General.urls')),
    url(r'^exam/', include('Exam.urls')),
    url(r'^backup/', include('BackupRestore.urls')),
    url(r'^internship/', include('Internship.urls')),
    url(r'^feedback/', include('Feedback.urls'))
    # url(r'^research/', include('Research.urls')),
    # url(r'^update/', include('Update.urls'))

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# urlpatterns += staticfiles_urlpatterns()

Exam/urls.py
from django.conf.urls import url

from Exam import views

app_name = "exam"
urlpatterns = [
    # /exam/add
    url(r'^add/$', views.exam_register, name='exam_register'),
    # /exam/detail
    url(r'^detail/$', views.exam_detail, name='exam_detail'),
    # /exam/get_subjects
    url(r'^get_subjects/$', views.get_subjects, name='get_subjects'),
    # /exam/view_exam
    url(r'^view_exam/$', views.view_exam, name='view_exam'),
    # /exam/manage_exam
    url(r'^manage_exam/$', views.manage_exam, name='manage_exam'),
    # /exam/set_rooms
    url(r'^set_rooms/$', views.set_rooms, name='set_rooms'),
    # /exam/ste_exam_time
    url(r'^set_exam_time/$', views.set_exam_time, name='set_exam_time'),
    # /exam/check_availability
    url(r'^check_availability/$', views.check_availability, name='check_availability'),
    # /exam/check_availability/exam_group
    url(r'^check_availability/(?P<still_schedule>[0-9]+)/$', views.check_availability, name='check_availability'),
    # /exam/android/types_of_exam/
    url(r'^android/types_of_exam/$', views.android_types_of_exam, name='android_types_of_exam'),
    # /exam/android/exam_subjects/
    url(r'^android/exam_subjects/$', views.android_subject_for_exam, name='android_subject_for_exam'),

]

Research/urls.py
from django.conf.urls import url

from . import views

app_name = 'Research'

urlpatterns = [

    url(r'enter/$', views.enter_paper, name='enter_paper'),

    url(r'view/$', views.view_paper, name='view_paper'),

]

Research/models.py
import datetime

from django.db import models
from django.utils import timezone

from Registration.models import Faculty


def faculty_directory_path(instance, filename):
    return 'Media/Faculty/{0}/Research/{1}'.format(instance.faculty.faculty_code, filename)


class Paper(models.Model):
    faculty = models.ForeignKey(Faculty, on_delete=models.CASCADE, null=True, blank=True)
    year = models.PositiveIntegerField(default=timezone.now().year)
    date = models.DateField(default=timezone.now)
    type = models.CharField(max_length=10)  # Paid/Unpaid
    title = models.CharField(max_length=200)
    medium = models.CharField(max_length=50)  # Journal/Conference
    conference_attended = models.BooleanField(default=False)  # Has attended the conference
    level = models.CharField(max_length=50)  # National/International
    medium_name = models.CharField(max_length=200)  # Journal/Conference Name
    distribution = models.CharField(max_length=50)  # Online/Print
    peer_reviewed = models.BooleanField()  # Yes/No
    isbn = models.CharField(max_length=25)
    impact_factor = models.FloatField()
    volume = models.CharField(max_length=20)
    domain = models.CharField(max_length=100)
    paper_with = models.CharField(max_length=20)  # BE Student/ ME Student/ PhD Student/ Self
    first_author = models.BooleanField()
    funds_from_college = models.PositiveIntegerField()
    other_info = models.CharField(max_length=200)
    files = models.FileField(upload_to=faculty_directory_path, null=True, blank=True)

Research/forms.py
from django import forms

from Research.models import Paper


class PublicationForm(forms.ModelForm):
    type = forms.ChoiceField(
        choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')],
        widget=forms.RadioSelect
    )

    level = forms.ChoiceField(
        choices=[('National', 'National'), ('International', 'International')],
        widget=forms.RadioSelect
    )

    conference_attended = forms.ChoiceField(
        choices=[('True', 'Yes'), ('False', 'No')],
        widget=forms.RadioSelect,
        required=False,
        label='Have you attended the conference?'
    )

    first_author = forms.ChoiceField(
        choices=[('True', 'Yes'), ('False', 'No')],
        widget=forms.RadioSelect,
        label='Are you the first author?'
    )

    medium = forms.ChoiceField(
        choices=[('Journal', 'Journal'), ('Conference', 'Conference')],
        widget=forms.RadioSelect,
    )

    paper_with = forms.ChoiceField(
        choices=[('BE Student', 'BE Student'), ('ME Student', 'ME Student'), ('PhD Student', 'PhD Student'),
                 ('Self', 'Self')]
    )

    distribution = forms.ChoiceField(
        choices=[('Online', 'Online'), ('Print', 'Print')],
        widget=forms.RadioSelect
    )

    peer_reviewed = forms.ChoiceField(
        choices=[('True', 'Yes'), ('False', 'No')],
        widget=forms.RadioSelect
    )

    class Meta:
        model = Paper

        widgets = {
            'date': forms.DateInput(attrs={'class': 'datepicker'}),
            'other_info': forms.Textarea
        }

        fields = '__all__'
        exclude = ['is_conference']

Research/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render

# Create your views here.
from Research.forms import PublicationForm
from Research.models import Paper
from Roles.models import RoleManager


def enter_paper(request):
    user = request.user
    if not user.is_anonymous:
        is_faculty = RoleManager.objects.filter(user=user, role__role='faculty')
        # is_student = RoleManager.objects.filter(user=user, role__role='student')
        if is_faculty:
            if request.method == "POST":
                form = PublicationForm(request.POST, request.FILES)
                # form.fields['faculty'] = user.faculty

                if form.is_valid():

                    paper_object = form.save(commit=False)
                    paper_object.faculty = user.faculty
                    paper_object.save()
                    return render(request, 'dashboard_faculty.html', {'success': 'Paper successfully submitted'})

                else:
                    return render(request, 'dashboard_faculty.html', {'error': 'Form not valid'})
            else:
                form = PublicationForm()
                return render(request, "enter_publication.html", {'form': form})
        else:
            return HttpResponse('Not faculty')
    else:
        return HttpResponseRedirect('/login/')


def view_paper(request):
    user = request.user
    if not user.is_anonymous:
        is_faculty = RoleManager.objects.filter(user=user, role__role='faculty')
        is_student = RoleManager.objects.filter(user=user, role__role='student')
        if is_faculty:
            if request.method == "POST":
                paper = request.POST.get('paper_selected')
                paper_obj = Paper.objects.get(pk=paper)
                return render(request, 'view_paper.html', {
                    'paper': paper_obj
                })
            else:
                return None
        else:
            return HttpResponse('Not faculty')
    else:
        return HttpResponseRedirect('/login/')

Research/templates/enter_publication.html
{% extends './dashboard_faculty.html' %}
{% block extra_style %}
    fieldset ul {
    list-style: none
    }

    ul#id_conference_attended li, ul#id_distribution li, ul#id_peer_reviewed li, ul#id_first_author li {
    display: inline;
    margin-right: 5px;
    }
    legend {
    text-align: center;
    }
{% endblock extra_style %}
{% block content %}
    <br>
    <br>
    <form method="post" action="{% url 'Research:enter_paper' %}" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="container">
            <div class="row">
                <fieldset class="col-lg-12">
                    <div class="col-lg-12 row">
                        <div class="col-lg-3"></div>
                        <div class="col-lg-6 center">
                            <legend>Publication Details</legend>
                        </div>
                    </div>
                    <div class="row">
                        {#                    <div class="col-lg-6 col-lg-offset-3">#}
                        {#                        <div class="form-element">#}
                        {#                            <span class="error">{{ form.faculty.errors }}</span>#}
                        {#                            <div class="col-lg-4">#}
                        {#                                {{ form.faculty.label_tag }}#}
                        {#                            </div>#}
                        {#                            <div class="col-lg-8">#}
                        {#                                {{ form.faculty }}{{ user.faculty.first_name }}#}
                        {#                            </div>#}
                        {#                        </div>#}
                        {#                    </div>#}
                        <div class="col-lg-6 col-lg-offset-3">
                            <div class="form-element">
                                <span class="error">{{ form.title.errors }}</span>
                                <div class="col-lg-4">
                                    {{ form.title.label_tag }}
                                </div>
                                <div class="col-lg-8">
                                    {{ form.title }}
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-element">
                                <span class="error">{{ form.year.errors }}</span>
                                <div class="col-lg-4">
                                    {{ form.year.label_tag }}
                                </div>
                                <div class="col-lg-8">
                                    {{ form.year }}
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-element">
                                <span class="error">{{ form.date.errors }}</span>
                                <div class="col-lg-4">
                                    {{ form.date.label_tag }}
                                </div>
                                <div class="col-lg-8">
                                    {{ form.date }}
                                </div>
                            </div>
                        </div>
                        <!--<div class="row">-->
                        <div class="col-lg-6">
                            <div class="form-element">
                                <span class="error">{{ form.medium.errors }}</span>
                                <div class="col-lg-4">
                                    {{ form.medium.label_tag }}
                                </div>
                                <div class="col-lg-8">
                                    {{ form.medium }}
                                </div>
                            </div>
                        </div>

                        <div class="col-lg-6">
                            <div class="form-element">
                                <span class="error">{{ form.medium_name.errors }}</span>
                                <div class="col-lg-4">
                                    {{ form.medium_name.label_tag }}
                                </div>
                                <div class="col-lg-8">
                                    {{ form.medium_name }}
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-12"></div>
                        <div class="col-lg-6 col-lg-offset-3" id="conference_attended" style="display: none">
                            <div class="form-element">
                                <span class="error">{{ form.conference_attended.errors }}</span>
                                <div class="col-lg-4">
                                    {{ form.conference_attended.label_tag }}
                                </div>
                                <div class="col-lg-8">
                                    {{ form.conference_attended }}
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-element">
                                <span class="error">{{ form.level.errors }}</span>
                                <div class="col-lg-4">
                                    {{ form.level.label_tag }}
                                </div>
                                <div class="col-lg-8">
                                    {{ form.level }}
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-element">
                                <span class="error">{{ form.type.errors }}</span>
                                <div class="col-lg-4">
                                    {{ form.type.label_tag }}
                                </div>
                                <div class="col-lg-8">
                                    {{ form.type }}
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-element">
                                <span class="error">{{ form.distribution.errors }}</span>
                                <div class="col-lg-4">
                                    {{ form.distribution.label_tag }}
                                </div>
                                <div class="col-lg-8">
                                    {{ form.distribution }}
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-element">
                                <span class="error">{{ form.peer_reviewed.errors }}</span>
                                <div class="col-lg-4">
                                    {{ form.peer_reviewed.label_tag }}
                                </div>
                                <div class="col-lg-8">
                                    {{ form.peer_reviewed }}
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-element">
                                <span class="error">{{ form.isbn.errors }}</span>
                                <div class="col-lg-4">
                                    {{ form.isbn.label_tag }}
                                </div>
                                <div class="col-lg-8">
                                    {{ form.isbn }}
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-element">
                                <span class="error">{{ form.impact_factor.errors }}</span>
                                <div class="col-lg-4">
                                    {{ form.impact_factor.label_tag }}
                                </div>
                                <div class="col-lg-8">
                                    {{ form.impact_factor }}
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-element">
                                <span class="error">{{ form.volume.errors }}</span>
                                <div class="col-lg-4">
                                    {{ form.volume.label_tag }}
                                </div>
                                <div class="col-lg-8">
                                    {{ form.volume }}
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-element">
                                <span class="error">{{ form.domain.errors }}</span>
                                <div class="col-lg-4">
                                    {{ form.domain.label_tag }}
                                </div>
                                <div class="col-lg-8">
                                    {{ form.domain }}
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-element">
                                <span class="error">{{ form.paper_with.errors }}</span>
                                <div class="col-lg-4">
                                    {{ form.paper_with.label_tag }}
                                </div>
                                <div class="col-lg-8">
                                    {{ form.paper_with }}
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-element">
                                <span class="error">{{ form.first_author.errors }}</span>
                                <div class="col-lg-4">
                                    {{ form.first_author.label_tag }}
                                </div>
                                <div class="col-lg-8">
                                    {{ form.first_author }}
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-element">
                                <span class="error">{{ form.funds_from_college.errors }}</span>
                                <div class="col-lg-4">
                                    {{ form.funds_from_college.label_tag }}
                                </div>
                                <div class="col-lg-8">
                                    {{ form.funds_from_college }}
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-element">
                                <span class="error">{{ form.other_info.errors }}</span>
                                <div class="col-lg-4">
                                    {{ form.other_info.label_tag }}
                                </div>
                                <div class="col-lg-8">
                                    {{ form.other_info }}
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-element">
                                <span class="error">{{ form.files.errors }}</span>
                                <div class="col-lg-4">
                                    {{ form.files.label_tag }}
                                </div>
                                <div class="col-lg-8">
                                    {{ form.files }}
                                </div>
                            </div>
                        </div>
                    </div>
                </fieldset>
            </div>


        </div>
        <br>
        <div class="container ">
            <input class="col-md-2 col-md-offset-5 btn btn-primary" type="submit">
        </div>
    </form>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    </body>
    <script>
        $(document).ready(function () {

            var mediumObj = document.getElementById('id_medium_0');
            mediumObj.setAttribute('onchange', 'showConferenceAttended(this)');
            mediumObj = document.getElementById('id_medium_1');
            mediumObj.setAttribute('onchange', 'showConferenceAttended(this)');

        });

        function showConferenceAttended(obj) {
            if (obj.value == 'Conference') {
                document.getElementById('conference_attended').style.display = "inline";
            }
            else {
                document.getElementById('conference_attended').style.display = "none";
            }
        }
    </script>
{% endblock content %}

Research/templates/view_paper.html
{% extends './dashboard_faculty.html' %}
{% block content %}
    <div class="container">
        <div class="row">
            <fieldset class="col-lg-12">
                <div class="col-lg-12 row">
                    <div class="col-lg-3"></div>
                    <div class="col-lg-6 text-center">
                        <legend>Publication Details</legend>
                    </div>
                </div>
                <div class="row">
                    <div class="col-lg-6 col-lg-offset-3">
                        <div class="form-element">
                            <div class="col-lg-5">
                                <label>Title</label>
                            </div>
                            <div class="col-lg-7">
                                {{ paper.title }}
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-element">
                            <div class="col-lg-4">
                                <label>Year</label>
                            </div>
                            <div class="col-lg-8">
                                {{ paper.year }}
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-element">
                            <div class="col-lg-4">
                                <label>Date Published</label>
                            </div>
                            <div class="col-lg-8">
                                {{ paper.date }}
                            </div>
                        </div>
                    </div>
                    <!--<div class="row">-->
                    <div class="col-lg-6">
                        <div class="form-element">
                            <div class="col-lg-4"><label>Medium of publication</label>
                            </div>
                            <div class="col-lg-8">
                                {{ paper.medium }}
                            </div>
                        </div>
                    </div>

                    <div class="col-lg-6">
                        <div class="form-element">
                            <div class="col-lg-4">
                                <label>{{ paper.medium }}</label>
                            </div>
                            <div class="col-lg-8">
                                {{ paper.medium_name }}
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-12"></div>
                    {% if paper.medium == 'Conference' %}
                        <div class="col-lg-6">
                            <div class="form-element">
                                <div class="col-lg-4"><label>Conference Attended</label></div>
                                <div class="col-lg-8">
                                    {% if paper.conference_attended == True %}Yes
                                    {% else %}No
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    {% endif %}
                    <div class="col-lg-6">
                        <div class="form-element">
                            <div class="col-lg-4"><label>Level</label></div>
                            <div class="col-lg-8">
                                {{ paper.level }}
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-element">
                            <div class="col-lg-4">
                                <label>Peer Reviewed</label>
                            </div>
                            <div class="col-lg-8">
                                {{ paper.type }}
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-element">
                            <div class="col-lg-4">
                                <label>Peer Reviewed</label>
                            </div>
                            <div class="col-lg-8">
                                {{ paper.distribution }}
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-element">
                            <div class="col-lg-4">
                                <label>Peer Reviewed</label>
                            </div>
                            <div class="col-lg-8">
                                {% if paper.peer_reviewed == True %}Yes
                                {% else %}No
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-element">
                            <div class="col-lg-4">
                                <label>ISBN</label>
                            </div>
                            <div class="col-lg-8">
                                {{ paper.isbn }}
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-element">
                            <div class="col-lg-4">
                                <label>Impact Factor</label>
                            </div>
                            <div class="col-lg-8">
                                {{ paper.impact_factor }}
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-element">
                            <div class="col-lg-4">
                                <label>Volume</label>
                            </div>
                            <div class="col-lg-8">
                                {{ paper.volume }}
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-element">
                            <div class="col-lg-4">
                                <label>Domain</label>
                            </div>
                            <div class="col-lg-8">
                                {{ paper.domain }}
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-element">
                            <div class="col-lg-4">
                                <label>Paper With</label>
                            </div>
                            <div class="col-lg-8">
                                {{ paper.paper_with }}
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-element">
                            <div class="col-lg-4">
                                <label>Are you the first author?</label>
                            </div>
                            <div class="col-lg-8">
                                {% if paper.first_author == True %}Yes
                                {% else %}No
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-element">
                            <div class="col-lg-4">
                                <label>Funds received from college</label>
                            </div>
                            <div class="col-lg-8">
                                &#8377;{{ paper.funds_from_college }}
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-element">
                            <div class="col-lg-4">
                                <label>Other Info</label>
                            </div>
                            <div class="col-lg-8">
                                {{ paper.other_info }}
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-element">
                            <div class="col-lg-4">
                                <label>Files</label>
                            </div>
                            <div class="col-lg-8">
                                <a href="{{ paper.files.url }}"
                                   style="text-decoration: underline;">{{ paper.files.name }}</a>
                            </div>
                        </div>
                    </div>
                </div>
            </fieldset>
        </div>


    </div>
{% endblock content %}