EnterpriseResourcePlanning/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

from EnterpriseResourcePlanning import views, settings

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^update/', include('Update.urls')),
    url(r'^register/', include('Registration.urls')),
    url(r'^attendance/', include('Attendance.urls')),
    # url(r'^administrator/', include('administrator.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^login/', include('Login.urls')),
    url(r'^dashboard/', include('Dashboard.urls')),
    url(r'^timetable/', include('Timetable.urls')),
    url(r'^request/', include('Requests.urls')),
    url(r'^report/', include('Report.urls')),
    url(r'^general/', include('General.urls')),
    url(r'^exam/', include('Exam.urls')),
    url(r'^backup/', include('BackupRestore.urls')),
    url(r'^internship/', include('Internship.urls')),
    url(r'^feedback/', include('Feedback.urls'))
    # url(r'^research/', include('Research.urls')),
    # url(r'^update/', include('Update.urls'))

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# urlpatterns += staticfiles_urlpatterns()

Exam/urls.py
from django.conf.urls import url

from Exam import views

app_name = "exam"
urlpatterns = [
    # /exam/add
    url(r'^add/$', views.exam_register, name='exam_register'),
    # /exam/detail
    url(r'^detail/$', views.exam_detail, name='exam_detail'),
    # /exam/get_subjects
    url(r'^get_subjects/$', views.get_subjects, name='get_subjects'),
    # /exam/view_exam
    url(r'^view_exam/$', views.view_exam, name='view_exam'),
    # /exam/manage_exam
    url(r'^manage_exam/$', views.manage_exam, name='manage_exam'),
    # /exam/set_rooms
    url(r'^set_rooms/$', views.set_rooms, name='set_rooms'),
    # /exam/ste_exam_time
    url(r'^set_exam_time/$', views.set_exam_time, name='set_exam_time'),
    # /exam/check_availability
    url(r'^check_availability/$', views.check_availability, name='check_availability'),
    # /exam/check_availability/exam_group
    url(r'^check_availability/(?P<still_schedule>[0-9]+)/$', views.check_availability, name='check_availability'),
    # /exam/android/types_of_exam/
    url(r'^android/types_of_exam/$', views.android_types_of_exam, name='android_types_of_exam'),
    # /exam/android/exam_subjects/
    url(r'^android/exam_subjects/$', views.android_subject_for_exam, name='android_subject_for_exam'),

]

Login/urls.py
from django.conf.urls import url, include

from . import views

app_name = 'login'

urlpatterns = [
    url(r'^$', views.login_user, name='login'),
    url(r'^android/$', views.android_login, name='login_android'),

]

Registration/urls.py
from django.conf.urls import url

from . import views

app_name = 'registration'

urlpatterns = [
    # /register/student - Register Student
    url(r'^student/$', views.register_student, name='register_student'),

    # /register/faculty - Register Faculty
    url(r'^faculty/$', views.register_faculty, name='register_faculty'),

    url(r'^branch/$', views.register_branch, name='register_branch'),

    url(r'^division/$', views.register_division, name='register_division'),

    # /register/subject - Register Subject
    url(r'^subject/$', views.register_subject, name='register_subject'),

    # /register/year - Register Year Details
    url(r'^year_detail/$', views.register_year_detail, name='register_year_detail'),

    # /register/studentsuccess/ - Register Student
    url(r'^student/success/$', views.success_student, name='success_student'),
    #     # /register/facultysuccess/ - Register Faculty
    url(r'^faculty/success/$', views.success_faculty, name='success_faculty'),

    # /register/view_subjects
    url(r'^view_subjects/$', views.view_subjects, name='view_subjects'),

    url(r'^register_faculty_subject/$', views.register_faculty_subject, name='register_faculty_subject'),

    # /states/
    url(r'^states/India$', views.get_states, name='get_states'),

    url(r'^test/$', views.test, name='test'),

    url(r'^get_division/$', views.get_division, name='get_division'),

    url(r'^get_shift/$', views.get_shift, name='get_shift'),
    # url(r'^change_password/$', views.change_password, name='change_password'),
    url(r'forgot_password/$', views.forgot_password, name='forgot_password'),

    url(r'change_password/$', views.change_password, name='change_password'),

    url(r'student_subject/$', views.student_subject, name='student_subject'),

    url(r'student_subject_division/$', views.student_subject_division, name='student_subject_division'),

    url(r'set_schedule_date/$', views.set_schedule_date, name='set_schedule_date'),

    # url(r'student_subject_registration/$', views.student_subject_registration, name='student_subject_registration'),

    url(r'year/$', views.register_year, name='register_year'),

    url(r'room/$', views.register_room, name='register_room'),

    url(r'^verification/email/(?P<key>[\w]+)/(?P<username>[\w]+)', views.verification_process,
        name="verification_process"),

]

Login/models.py
from django.db import models

# Create your models here.

Login/views.py
from __future__ import unicode_literals

import hashlib
import json

from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.core.mail import send_mail
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.shortcuts import render
from django.utils.crypto import get_random_string
from django.views.decorators.csrf import csrf_exempt

from EnterpriseResourcePlanning import conf
from EnterpriseResourcePlanning.conf import email_sending_service_enabled
from General.models import StudentDetail, Division, FacultySubject
from Registration.models import Faculty, Student, Branch
from Timetable.models import Timetable
from Roles.models import  RoleManager
import json


def login_user(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return HttpResponseRedirect('/dashboard/')
        else:
            return render(request, 'login.html', {'error': 'Invalid credentials'})
    elif request.method == "GET":
        user = request.user
        if user.is_anonymous:
            return render(request, 'login.html')
        else:
            return HttpResponseRedirect('/dashboard/')

    return render(request, 'login.html')


@csrf_exempt
def android_login(request):
    response = {
        'user_type': 'null'
    }
    if request.method == 'POST':
        try:
            print(request.POST)
            username = request.POST.get('username')
            password = request.POST.get('password')
            user = authenticate(username=username, password=password)
            if user:

                user = User.objects.get(username=username)
                # print(user.role)
                is_faculty = RoleManager.objects.filter(user=user, role__role='faculty')
                is_student = RoleManager.objects.filter(user=user, role__role='student')
                if is_faculty:
                    faculty = user.faculty
                    faculty_response = {
                        'user_type': 'Faculty',
                        'initials': user.faculty.initials,
                        'name': user.faculty.first_name + user.faculty.last_name,
                    }

                    # Add subjects taught by faculty division-wise

                    theory = FacultySubject.objects.filter(faculty=user.faculty, subject__is_practical=False, is_active=True)
                    practical = FacultySubject.objects.filter(faculty=user.faculty, subject__is_practical=True, is_active=True)
                    subject_json = {}
                    theory_json = {}
                    practical_json = {}
                    for each in theory:
                        if each.division is not None:
                            theory_json[each.division.division] = []
                    for each in theory:
                        if each.division is not None:
                            theory_json[each.division.division] += [each.subject.short_form]
                    for each in practical:
                        if each.division is not None:
                            practical_json[each.division.division] = []
                    for each in practical:
                        if each.division is not None:
                            practical_json[each.division.division] += [each.subject.short_form]

                    subject_json['theory'] = theory_json
                    subject_json['practical'] = practical_json
                    faculty_response['subjects'] = subject_json
                    print("Subject JSON", subject_json)

                    # return HttpResponse(str(faculty_response))
                    all_divisions = Division.objects.filter().all()

                    attendance_list = {}

                    for each_division in all_divisions:

                        all_student = [each.student for each in
                                       StudentDetail.objects.filter(batch__division=each_division).distinct()]

                        year = each_division.year_branch.year.year

                        division = each_division.division
                        branch = each_division.year_branch.branch.branch

                        if year in attendance_list:

                            if branch in attendance_list[year]:
                                if division in attendance_list[year][branch]:
                                    pass
                                else:
                                    attendance_list[year][branch][division] = {}
                            else:
                                attendance_list[year][branch] = {}
                                attendance_list[year][branch][division] = {}

                        else:
                            attendance_list[year] = {}
                            attendance_list[year][branch] = {}
                            attendance_list[year][branch][division] = {}
                        # attendance_list[year][branch][division] = sorted([
                        #     StudentRollNumber.objects.get(student=each_student.student, is_active=True) for
                        #     each_student in all_student])

                        for each_student in all_student:

                            roll_number = StudentDetail.objects.get(student=each_student,
                                                                       is_active=True).roll_number

                            if 'all' in attendance_list[year][branch][division]:
                                attendance_list[year][branch][division]['all'].append(roll_number)
                            else:
                                attendance_list[year][branch][division]['all'] = []
                                attendance_list[year][branch][division]['all'].append(roll_number)
                            curr_batch = StudentDetail.objects.get(student=each_student, is_active=True).batch.batch_name
                            if curr_batch in attendance_list[year][branch][division]:
                                attendance_list[year][branch][division][curr_batch].append(roll_number)
                            else:
                                attendance_list[year][branch][division][curr_batch] = []
                                attendance_list[year][branch][division][curr_batch].append(roll_number)

                            # attendance_list[year][branch][division] = {}
                        #
                        # for each_student in all_student:
                        #     attendance_list[year][branch][division].appned(
                        #         StudentRollNumber.objects.get(student=each_student, is_active=True).roll_number)

                    faculty_response['attendance_list'] = attendance_list
                    print(HttpResponse(json.dumps(faculty_response)))
                    return HttpResponse(json.dumps(faculty_response))
                elif is_student:
                    student = user.student
                    student_detail = StudentDetail.objects.get(student=student, is_active=True)

                    student_response = {
                        'user_type': 'Student',
                        'year': student_detail.batch.division.year_branch.year.year,
                        'branch': student_detail.batch.division.year_branch.branch.branch,
                        'division': student_detail.batch.division.division,
                        'batch': student_detail.batch.batch_name,
                        'name': user.student.first_name + user.student.last_name
                    }
                    print(student_response)
                    return JsonResponse(student_response)
            else:
                return JsonResponse(response)

        except Exception as ex:
            template = "An exception of type {0} occurred. Arguments:\n{1!r}"
            message = template.format(type(ex).__name__, ex.args)

            return JsonResponse(message)
    else:
        return render(request, 'login.html')


def generate_activation_key():
    chars = 'abcdefghijklmnopqrstuvwxyz0123456789'
    secret_key = get_random_string(20, chars)

    return hashlib.sha256((secret_key).encode('utf-8')).hexdigest()

Login/templates/change_password.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block head %}
    <style>
        body, html, .row-offcanvas {
            height: 100%;
        }

        body {
            padding-top: 50px;
            background: #F1F1F1;
        }

        #sidebar {
            width: inherit;
            min-width: 220px;
            max-width: 220px;
            background-color: #F1F1F1;
            float: left;
            height: 100%;
            position: relative;
            overflow-y: auto;
            overflow-x: hidden;
        }

        #main {
            height: 100%;
            overflow: auto;
        }

        /*Media query for small screen toggle*/
        @media screen and (max-width: 768px) {
            .row-offcanvas {
                position: relative;
                -webkit-transition: all 0.25s ease-out;
                -moz-transition: all 0.25s ease-out;
                transition: all 0.25s ease-out;
                width: calc(100% + 220px);
            }

            .row-offcanvas-left {
                left: -220px;
            }

            .row-offcanvas-left.active {
                left: 0;
            }

            .sidebar-offcanvas {
                position: absolute;
                top: 0;
            }
        }

        /*Media query for small screen toggle ENDS*/

        /*Extra style for main contents div*/
        .back {
            background: #ffffff;
            height: 100%;
        }

        .nav-stacked {
            padding-top: 5px;
        }

        .col-md-8 {
            padding: 15px;
        }

        .btn {
            border-radius: 0;
        }

        input {
            padding: 5px;
        }
    </style>


{% endblock %}
{% block body %}

    <!--Main content-->
    <div id="main">
        <div class="col-md-8 center-block">
            <!--Toggle for sidebar nav-->


            <form action="{% url 'registration:verification_process' key gr_number %}" method="post">
                {% csrf_token %}
                <input name="gr_number" value="{{ gr_number }}" type="hidden">
                <input name="key" value="{{ key }}" type="hidden">

                <div class="row">
                    <label>New password:</label>
                    <input type="text" class="form-control" name="new_pwd">
                </div>
                <div class="row">
                    <label>Confirm new password:</label>
                    <input type="text" class="form-control" name="cnf_pwd">
                </div>
                <button type="submit" class="btn btn-primary" name="submit" value="submit">Change</button>
            </form>
        </div>
    </div>
{% endblock %}

Login/templates/forgot_password.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block head %}
    <style>
        body, html, .row-offcanvas {
            height: 100%;
        }

        body {
            padding-top: 50px;
            background: #F1F1F1;
        }

        #sidebar {
            width: inherit;
            min-width: 220px;
            max-width: 220px;
            background-color: #F1F1F1;
            float: left;
            height: 100%;
            position: relative;
            overflow-y: auto;
            overflow-x: hidden;
        }

        #main {
            height: 100%;
            overflow: auto;
        }

        /*Media query for small screen toggle*/
        @media screen and (max-width: 768px) {
            .row-offcanvas {
                position: relative;
                -webkit-transition: all 0.25s ease-out;
                -moz-transition: all 0.25s ease-out;
                transition: all 0.25s ease-out;
                width: calc(100% + 220px);
            }

            .row-offcanvas-left {
                left: -220px;
            }

            .row-offcanvas-left.active {
                left: 0;
            }

            .sidebar-offcanvas {
                position: absolute;
                top: 0;
            }
        }

        /*Media query for small screen toggle ENDS*/

        /*Extra style for main contents div*/
        .back {
            background: #ffffff;
            height: 100%;
        }

        .nav-stacked {
            padding-top: 5px;
        }

        .col-md-8 {
            padding: 15px;
        }

        .btn {
            border-radius: 0;
        }

        input {
            padding: 5px;
        }
    </style>
{% endblock %}
{% block body %}

    <!--Main content-->
    <div id="main">
        <div class="col-md-4 center-block">
            <!--Toggle for sidebar nav-->


            <form action="" method="post">
                {% csrf_token %}
                <div class="row">
                    <label>Enter Your GR Number:</label>
                    <input type="text" class="form-control" name="gr_number">
                </div>
                <button type="submit" class="btn btn-primary" name="submit" value="submit">Reset</button>
            </form>
        </div>
    </div>
{% endblock %}

Login/templates/login.html
{% extends "./base.html" %}
{% block title %}
    Login | ERP
{% endblock title %}
{% block style %}
    <style>
        .navbar-default {
            display: none !important;
        }

        .login-form {
            width: 25%;
            border: 1px solid #d8dee2;
            border-radius: 5px;
            display: inline-block;
            background: white;
            text-align: center;
            padding: 18px;
        }

        html, body {
            background: #F9F9F9;
        }

        .navbar-brand {
            display: inline-block;
            font-size: 4em;
            font-weight: bolder;
            margin: 25px 0;
            float: none;
        }

        .container {
            text-align: center;
        }

        input {
            border: 1px solid rgba(186, 186, 186, 0.35);
            border-radius: 4px;
            width: 94%;
            padding: 5px;
        }

        .logo {
            text-align: center;
        }

        .control-label {
            margin-left: 10px;
            float: left;
            font-weight: 500;
        }

        .form-heading {
            font-size: 2em;
        }

        #submit {
            color: #fff;
            background-color: #0379C4;
            background-image: linear-gradient(-180deg, #0399ee 0%, #0379C4 90%);
        }

        @media only screen and (max-width: 767px) {
            .login-form {
                width: 100%;
            }
        }
    </style>
{% endblock style %}
{% block body %}
    <body>

    <div class="logo">
        <a class="navbar-brand" href="/"><i class="glyphicon glyphicon-flash"></i></a>

        <p class="form-heading">Sign in to ERP</p>
    </div>
    <form method="post" action="{% url 'login:login' %}" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="container">
            <div class="login-form">
                <div>
                    <div class="form-element">
                        <span class="error">{{ form.first_name.errors }}</span>
                        <label class="control-label" style="display: block">Username</label>
                        <input type="text" id="username" name="username">
                    </div>
                    <div class="form-element col-centered">
                        <label class="control-label" style="display: block">Password</label>
                        <input type="password" id="password" name="password">
                    </div>
                    <input class="btn" id="submit" type="submit" value="Sign in">

                    <a class="btn" href="{% url 'registration:register_student' %}">Register as a new student</a><br/>

                    <a href="{% url 'registration:forgot_password' %}">Forgot Password?</a>
                </div>
            </div>
        </div>
    </form>
    </body>
{% endblock body %}