EnterpriseResourcePlanning/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

from EnterpriseResourcePlanning import views, settings

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^update/', include('Update.urls')),
    url(r'^register/', include('Registration.urls')),
    url(r'^attendance/', include('Attendance.urls')),
    # url(r'^administrator/', include('administrator.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^login/', include('Login.urls')),
    url(r'^dashboard/', include('Dashboard.urls')),
    url(r'^timetable/', include('Timetable.urls')),
    url(r'^request/', include('Requests.urls')),
    url(r'^report/', include('Report.urls')),
    url(r'^general/', include('General.urls')),
    url(r'^exam/', include('Exam.urls')),
    url(r'^backup/', include('BackupRestore.urls')),
    url(r'^internship/', include('Internship.urls')),
    url(r'^feedback/', include('Feedback.urls'))
    # url(r'^research/', include('Research.urls')),
    # url(r'^update/', include('Update.urls'))

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# urlpatterns += staticfiles_urlpatterns()

Exam/urls.py
from django.conf.urls import url

from Exam import views

app_name = "exam"
urlpatterns = [
    # /exam/add
    url(r'^add/$', views.exam_register, name='exam_register'),
    # /exam/detail
    url(r'^detail/$', views.exam_detail, name='exam_detail'),
    # /exam/get_subjects
    url(r'^get_subjects/$', views.get_subjects, name='get_subjects'),
    # /exam/view_exam
    url(r'^view_exam/$', views.view_exam, name='view_exam'),
    # /exam/manage_exam
    url(r'^manage_exam/$', views.manage_exam, name='manage_exam'),
    # /exam/set_rooms
    url(r'^set_rooms/$', views.set_rooms, name='set_rooms'),
    # /exam/ste_exam_time
    url(r'^set_exam_time/$', views.set_exam_time, name='set_exam_time'),
    # /exam/check_availability
    url(r'^check_availability/$', views.check_availability, name='check_availability'),
    # /exam/check_availability/exam_group
    url(r'^check_availability/(?P<still_schedule>[0-9]+)/$', views.check_availability, name='check_availability'),
    # /exam/android/types_of_exam/
    url(r'^android/types_of_exam/$', views.android_types_of_exam, name='android_types_of_exam'),
    # /exam/android/exam_subjects/
    url(r'^android/exam_subjects/$', views.android_subject_for_exam, name='android_subject_for_exam'),

]

Exam/models.py
from django.db import models

# Create your models here.
from General.models import Division, Semester, StudentSubject, YearBranch
from Registration.models import Subject, Faculty
from Timetable.models import Room


class ExamMaster(models.Model):
    exam_name = models.CharField(max_length=300)
    # Below 2 fields would be filled at the time of active/inactive
    start_date = models.DateField()
    end_date = models.DateField(null=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.exam_name


class ExamDetail(models.Model):
    exam = models.ForeignKey(ExamMaster, on_delete=models.CASCADE)
    year = models.ForeignKey(YearBranch, on_delete=models.CASCADE)
    semester = models.ForeignKey(Semester, on_delete=models.CASCADE)
    schedule_start_date = models.DateField()
    schedule_end_date = models.DateField()
    is_active = models.BooleanField(default=True)


class ExamSubject(models.Model):
    exam = models.ForeignKey(ExamDetail, on_delete=models.CASCADE)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    coordinator = models.ForeignKey(Faculty, on_delete=models.CASCADE)
    start_datetime = models.DateTimeField(null=True)
    end_datetime = models.DateTimeField(null=True)
    is_active = models.BooleanField(default=True)


class ExamGroup(models.Model):
    name = models.CharField(max_length=100)
    is_active = models.BooleanField(default=True)


class ExamGroupDetail(models.Model):
    exam_group = models.ForeignKey(ExamGroup, on_delete=models.CASCADE)
    exam = models.ForeignKey(ExamDetail, on_delete=models.CASCADE)
    is_active = models.BooleanField(default=True)


class ExamGroupRoom(models.Model):
    exam_group = models.ForeignKey(ExamGroup, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    is_active = models.BooleanField(default=True)


class Mark(models.Model):
    exam = models.ForeignKey(ExamDetail, on_delete=models.CASCADE)
    student_subject = models.ForeignKey(StudentSubject, on_delete=models.CASCADE)
    max_total = models.IntegerField()


class MarksType(models.Model):
    type_of_marks = models.CharField(max_length=200)
    marks = models.ForeignKey(Mark, on_delete=models.CASCADE)
    marks_obtained = models.IntegerField()
    max_marks = models.PositiveIntegerField()
    cut_off_marks = models.IntegerField(default=0)


class ExamSubjectRoom(models.Model):
    exam_subject = models.ForeignKey(ExamSubject, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)


class ExamSubjectStudentRoom(models.Model):
    exam_subject_room = models.ForeignKey(ExamSubjectRoom, on_delete=models.CASCADE)
    student_subject = models.ForeignKey(StudentSubject, on_delete=models.CASCADE)

    def __str__(self):
        return self.exam_subject_room.exam_subject.exam.exam.exam_name + self.exam_subject_room.exam_subject.subject.short_form

Exam/forms.py
from django import forms

from Exam.models import ExamDetail, ExamMaster
from General.models import YearBranch, Semester


class ExamDetailForm(forms.ModelForm):
    # subjects = forms.ModelMultipleChoiceField(queryset=.objects.all(), required=False,
    #                                              widget=forms.CheckboxSelectMultiple)

    def __init__(self, *args, **kwargs):
        super(ExamDetailForm, self).__init__(*args, **kwargs)
        self.fields['exam'].queryset = ExamMaster.objects.filter(is_active=True)
        self.fields['year'].queryset = YearBranch.objects.filter(is_active=True)
        self.fields['semester'].queryset = Semester.objects.filter(is_active=True)
        for field in self.fields:
            if field not in ['schedule_start_date', 'schedule_end_date']:
                self.fields[field].widget.attrs.update({'class': 'form-control', })

    class Meta:
        widgets = {
            'schedule_start_date': forms.DateInput(attrs={'class': 'datepicker form-control'}),
            'schedule_end_date': forms.DateInput(attrs={'class': 'datepicker form-control'}),
        }

        model = ExamDetail
        fields = '__all__'
        exclude = ['is_active']

    def clean(self):
        cleaned_data = super().clean()
        schedule_start_date = cleaned_data.get('schedule_start_date')
        schedule_end_date = cleaned_data.get('schedule_end_date')

        if schedule_end_date and schedule_start_date:
            if schedule_end_date < schedule_end_date:
                raise forms.ValidationError("End date should be less than start date")

Exam/views.py
import json
from collections import defaultdict
from operator import attrgetter

from django.db.models import Q
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect
import datetime
import dateutil.parser

# Create your views here.
from django.views.decorators.csrf import csrf_exempt

from Exam.forms import ExamDetailForm
from Exam.models import ExamMaster, ExamSubject, ExamDetail, ExamGroupDetail, ExamGroupRoom, ExamSubjectRoom, \
    ExamSubjectStudentRoom, ExamGroup
from General.models import Semester, BranchSubject, CollegeYear, YearBranch, FacultySubject, Division, StudentDetail, \
    StudentSubject
from General.views import notify_users
from Registration.models import Branch, Student
from Registration.views import has_role
from Timetable.models import Room


def exam_register(request):
    class_active = "exam"
    if request.method == 'GET':
        return render(request, 'exam_register.html', {
            'class_active': class_active,

        })

    else:
        exam_name = request.POST.get('exam_name')
        ExamMaster.objects.create(exam_name=exam_name, start_date=datetime.date.today())
        context = {'success': "Successfully registered"}
        return render(request, 'exam_register.html', context)


def exam_detail(request):
    class_active = 'exam'
    if request.method == "GET":
        return render(request, 'exam_detail.html', {
            'class_active': class_active,
            'form': ExamDetailForm
        })
    else:
        form = ExamDetailForm(request.POST)
        if form.is_valid():
            exam_detail_obj = form.save()
            subjects = request.POST.getlist('subject')

            for each_subject in subjects:
                subject = BranchSubject.objects.get(is_active=True, year_branch=exam_detail_obj.year,
                                                    subject__short_form=each_subject).subject
                faculty_initials = request.POST.get(each_subject + '_faculty')

                faculty_obj = FacultySubject.objects.filter(faculty__initials=faculty_initials, is_active=True,
                                                            subject=subject)[0].faculty

                ExamSubject.objects.create(exam=exam_detail_obj, subject=subject, coordinator=faculty_obj,
                                           is_active=True)

            return render(request, 'set_exam_time.html', {
                'subjects': subjects,
                'exam_name': exam_detail_obj.exam.exam_name,
                'branch': exam_detail_obj.year.branch.branch,
                'year': exam_detail_obj.year.year,
                'exam_pk': exam_detail_obj.id,
            })
        else:
            return render(request, 'exam_detail.html', {
                'class_active': class_active,
                'form': form,
                'error': 'Not valid'
            })


def set_exam_time(request):
    user = request.user

    if has_role(user, 'faculty'):
        if request.method == 'POST':
            exam_pk = request.POST.get('exam_pk')
            exam_detail_obj = ExamDetail.objects.get(id=exam_pk)

            subjects = request.POST.getlist('subject')

            # Notify students about exam
            notification_type = 'general'
            message = 'Your ' + exam_detail_obj.exam.exam_name + ' exam has been scheduled from ' + \
                      exam_detail_obj.schedule_start_date.__str__() + ' to ' + exam_detail_obj.schedule_end_date.__str__() + \
                      ' for subjects ' + ", ".join(subjects)
            heading = 'Exam Schedule for ' + exam_detail_obj.exam.exam_name

            year_branch_obj = exam_detail_obj.year
            division = list(Division.objects.filter(is_active=True, year_branch=year_branch_obj))

            notify_users(notification_type=notification_type, message=message, heading=heading, division=division)

            # Add to examsubject
            user_obj = []
            for each_exam_subject in exam_detail_obj.examsubject_set.all():
                each_subject = each_exam_subject.subject.short_form

                exam_start_time = dateutil.parser.parse(request.POST.get('start_' + each_subject))
                exam_end_time = dateutil.parser.parse(request.POST.get('end_' + each_subject))

                each_exam_subject.start_datetime = exam_start_time
                each_exam_subject.end_datetime = exam_end_time

                each_exam_subject.save()
                # each_exam_subject.start_datetime

                # user_obj.append(faculty_obj.user)
                # Notify Faculty about exam
                notification_type = 'specific'
                message = 'You have been selected as Exam coordinator for ' + exam_detail_obj.exam.exam_name + ' exam which is scheduled from ' + \
                          exam_detail_obj.schedule_start_date.__str__() + ' to ' + exam_detail_obj.schedule_end_date.__str__() + \
                          ' for subject ' + each_subject
                heading = 'Exam Schedule for ' + exam_detail_obj.exam.exam_name

                # year_branch_obj = exam_detail_obj.year
                # division = list(Division.objects.filter(is_active=True, year_branch=year_branch_obj))

                # Notify Exam co-ordinator
                notify_users(notification_type=notification_type, message=message, heading=heading,
                             users_obj=[each_exam_subject.coordinator.user],
                             user_type='faculty')

            return redirect('/')


def get_subjects(request):
    if request.is_ajax():
        if request.method == "POST":
            year = request.POST.get('year')
            semester = request.POST.get('semester')
            semester_obj = Semester.objects.get(pk=semester)
            # year_splitted = year.split(' ')
            # branch = year_splitted[0]
            # year = year_splitted[1]
            # branch_obj = Branch.objects.get(branch=branch)
            # year_obj = CollegeYear.objects.get(year=year)
            year_branch_obj = YearBranch.objects.get(pk=year)

            subjects = BranchSubject.objects.filter(year_branch=year_branch_obj, semester=semester_obj, is_active=True)

            subject_faculty_json = {}

            for each_subject in subjects:
                short_form = each_subject.subject.short_form
                facultys = set(FacultySubject.objects.filter(subject=each_subject.subject, is_active=True).values_list(
                    'faculty__initials', flat=True))
                subject_faculty_json[short_form] = list(facultys)

            return HttpResponse(json.dumps(subject_faculty_json))

        else:
            return HttpResponse("Not post")
    else:
        return HttpResponse('Not ajax')


def view_exam(request):
    user = request.user
    if not user.is_anonymous:
        if has_role(user, 'faculty'):
            faculty = user.faculty
            # data = {}
            exam = []
            subjects = []
            all_exam_groups = ExamGroup.objects.filter(is_active=True)
            for each in all_exam_groups:
                exam_objs = each.examgroupdetail_set.filter(is_active=True)
                exam.append(exam_objs)

                for each_exam in exam_objs:
                    subjects.append(each_exam.exam.examsubject_set.filter(is_active=True))

            return render(request, 'view_exam.html', {
                'exam_group': all_exam_groups,
                'exam_group_detail': exam,
                'subjects': subjects
            })
        else:
            return redirect('/login/')
    else:
        return redirect('/login/')


def manage_exam(request):
    user = request.user
    class_active = "exam"
    if user.is_anonymous:
        return redirect('/login/')

    else:
        if has_role(user, 'faculty'):
            all_exams = ExamDetail.objects.all().order_by('-schedule_start_date')

            return render(request, 'manage_exam.html', {
                'class_active': class_active,
                'all_exams': all_exams
            })


def set_rooms(request):
    user = request.user
    if has_role(user, 'faculty'):
        if request.method == 'GET':
            all_exams = list(ExamDetail.objects.filter(is_active=True))
            all_exam_groups = ExamGroup.objects.filter(is_active=True)
            # used_exams = [each.examgroupdetail_set for each in all_exam_groups]
            done_exams = set([each.exam for each in ExamGroupDetail.objects.filter(is_active=True)])
            remaining = list(set(all_exams) - done_exams)
            print(remaining)
            # branch_obj = Branch.objects.get(branch='Computer')
            available_rooms = Room.objects.filter(is_active=True)
            return render(request, 'set_rooms.html', {
                'exams': remaining,
                'available_rooms': available_rooms
            })
        elif request.method == 'POST':
            all_exam_id = request.POST.getlist('exam')

            all_room_id = request.POST.getlist('room')



        else:
            return HttpResponse("Something went wrong")

    else:
        return HttpResponse('Access Denied')


def daterange(start_date, end_date):
    for n in range(int((end_date - start_date).days + 1)):
        yield start_date + datetime.timedelta(n)


def check_availability(request, still_schedule='0'):
    if request.is_ajax():
        if request.method == 'POST':
            if request.POST.get('exam_group'):
                exam_group_pk = int(request.POST.get('exam_group'))

                exam_group_obj = ExamGroup.objects.filter(pk=exam_group_pk)

                if exam_group_obj.__len__() < 1:
                    return HttpResponse('Not Found')

                exam_group_obj = exam_group_obj[0]

                exam_group_detail_objs = exam_group_obj.examgroupdetail_set.all()
                exam_detail_objs = [each.exam for each in exam_group_detail_objs]

Exam/templates/exam_detail.html
{% extends 'dashboard_faculty.html' %}
{% block title %}
    Exam-Regsiter | ERP
{% endblock title %}
{% block extra_style %}
    label{
    margin-left:0;
    }
    .subject-name{
    font-size:1.2em;
    }
    .subject-checkbox{
    margin-right:10px!important;
    }
{% endblock extra_style %}
{% block content %}
    <div class="row col-md-6">

        <form method="POST" action="{% url 'exam:exam_detail' %}">
            {% csrf_token %}

            <div class="form-group">
                {% for each in form %}
                    {{ each.errors }}
                    <label>{{ each.label }}</label>
                    {{ each }}
                {% endfor %}</div>
            <div id="div_subject" class=""></div>
            <br>
            <div class="col-lg-12">
                <input type="submit" class="btn btn-primary">
            </div>
        </form>

    </div>

    <script>


        $(".datepicker").datepicker({
            dateFormat: 'yy-mm-dd'
        });

        function call_ajax() {
            // code
            let year_obj = document.getElementById('id_year');
            let semester_obj = document.getElementById('id_semester');
            if (year_obj.value !== "" && semester_obj.value !== "") {
                $.ajax({
                    type: "POST",
                    url: '{% url 'exam:get_subjects' %}',
                    data: {
                        'csrfmiddlewaretoken': '{{ csrf_token }}',
                        'year': year_obj.value,
                        'semester': semester_obj.value
                    },
                    success: function (data) {
                        {#loading.style.display = "none";#}
                        {#main_content.style.opacity = 1;#}
                        {#if (room.value !== 'all') {#}
                        {#    let file_path = '/' + data + '.xlsx';#}
                        {#    let a = document.createElement('a');#}
                        {#    a.href = file_path;#}
                        {#    a.click();#}

                        {#alert(data);#}
                        let div = document.getElementById('div_subject');
                        $("#div_subject").empty();
                        let subjects = JSON.parse(data);
                        console.log(subjects);
                        for (each in subjects) {
                            {#console.log(each);#}
                            {#alert(each);#}
                            console.log(each);
                            let div_inside = document.createElement('div');
                            div_inside.className = "col-lg-6";
                            let checkbox = document.createElement('input');
                            checkbox.type = "checkbox";
                            checkbox.name = "subject";
                            checkbox.value = each;
                            checkbox.id = "id_" + each;
                            checkbox.className = "subject-checkbox";

                            let label = document.createElement('label');
                            label.htmlFor = "id_" + each;
                            label.className = "subject-name";
                            label.appendChild(document.createTextNode(each));
                            div_inside.appendChild(checkbox);
                            div_inside.appendChild(label);
                            div.appendChild(div_inside);

                            let combo_box = document.createElement('select');
                            combo_box.name = each + '_faculty';
                            let opt;
                            for (let each_faculty in subjects[each]) {

                                opt = document.createElement('option');
                                opt.value = subjects[each][each_faculty];
                                opt.innerHTML = subjects[each][each_faculty];
                                combo_box.appendChild(opt);
                            }
                            div_inside.appendChild(combo_box);
                        }


                    }

                });
            }
        }

        $('#id_year').on('change', function () {
            call_ajax();
        });
        $('#id_semester').on('change', function () {
            call_ajax();
        });


    </script>

{% endblock content %}

Exam/templates/exam_register.html
{% extends 'dashboard_faculty.html' %}
{% block title %}
    Exam-Regsiter | ERP
{% endblock title %}

{% block extra_style %}
    label{
    margin-left: 0;
    }
    .form-control{
    margin-bottom:20px;
    }
{% endblock extra_style %}
{% block content %}
    <div class="row col-md-3">
        <form method="POST" action="{% url 'exam:exam_register' %}">
            {% csrf_token %}
            <label for="exam_name">Name:</label>
            <input type="text" name="exam_name" id="exam_name" class="form-control">
            <input type="submit" class="btn btn-primary form-row">
            <div id="div_subject"></div>
        </form>

    </div>


{% endblock content %}

Exam/templates/set_exam_time.html
{% extends 'dashboard_faculty.html' %}
{% block title %}
    Exam-Schedule | ERP
{% endblock title %}


{% block content %}


    <form method="post" action="{% url 'exam:set_exam_time' %}">
    {% csrf_token %}
        Branch:{{ branch }}
        Year:{{ year }}
        Exam:{{ exam_name }}
        <input type="hidden" value="{{ exam_pk }}" name="exam_pk">
        <table>
            <thead>
            <tr>
                <th>Sr No</th>
                <th>Subject</th>
                <th>Start Time</th>
            </tr>
            </thead>
            {% for each_subject in subjects %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td><input type="text" readonly value="{{ each_subject }}"
                               id="{{ each_subject }}" name="subject"></td>
                    <td>
                        <div class="form-group">
                            <div class="input-append date">
                                <input size="16" class="form_datetime" name="start_{{ each_subject }}">
                                <input size="16" class="form_datetime" name="end_{{ each_subject }}">
                                <span class="add-on"><i class="icon-calendar"></i></span>
                            </div>
                        </div>
                    </td>

                </tr>
            {% endfor %}
        </table>
        <input type="submit" value="Submit">
    </form>


{% endblock content %}

{% block on_ready %}
    $(".form_datetime").datetimepicker({
    autoclose: true,
    todayBtn: true,
    startDate: notifications_json['today'] + " 10:00",
    minuteStep: 10
    });
{% endblock on_ready %}

Exam/templates/view_exam.html
{% extends 'dashboard_faculty.html' %}
{% load exam_extra %}

{% block title %}
    Exam-Schedule | ERP
{% endblock title %}



{% block content %}
    <div>

        {% for each_exam in exam_group_detail|get_at_index:forloop.counter0 %}
            <h3>{{ each_exam.exam.year.branch.branch }}&nbsp; - {{ each_exam.exam.year.year }}&nbsp;
                - {{ each_exam.exam.exam.exam_name }}</h3>
            {% for each_subject in subjects|get_at_index:forloop.counter0 %}
                {{ each_subject.subject }}
            {% endfor %}
        {% endfor %}

    </div>

    <div id="accordion" class="panel-group">
        {% for each in exam_group %}
            <div class="panel panel-default">
                <div class="panel-heading">
                    <a class="panel-title" data-toggle="collapse" data-parent="#accordion"
                       href="#collapse_{{ forloop.counter0 }}"><h4>{{ each.name }}</h4></a>
                    <button class="btn btn-info" onclick="showSchedule({{ each.pk }})">View Schedule</button>
                </div>
                <div id="collapse_{{ forloop.counter0 }}" class="panel-collapse collapse">
                    <div class="panel-body">
                        {% for each_exam in exam_group_detail|get_at_index:forloop.counter0 %}
                            <h5>{{ each_exam.exam.year.branch.branch }}&nbsp; - {{ each_exam.exam.year.year }}&nbsp;
                                - {{ each_exam.exam.exam.exam_name }}</h5>
                            {% for each_subject in subjects|get_at_index:forloop.counter0 %}
                                {{ each_subject.subject }}<br/>
                            {% endfor %}<br/><br/>
                        {% endfor %}
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

{% endblock content %}
{% block html %}
    <script>
        function showSchedule(id) {
            $.ajax({
                type: "POST",
                url: '{% url 'exam:check_availability' %}',
                data: {
                    'csrfmiddlewaretoken': '{{ csrf_token }}',
                    'exam_group': id
                },
                success: function (data) {
                    var data = JSON.parse(data);
                    let modalTitle = document.getElementById("modal-title");
                    modalTitle.innerText = "Schedule";

                    let modal_p = document.getElementById('modal-body-text');

                    while (modal_p.hasChildNodes()) {
                        modal_p.removeChild(modal_p.childNodes[0]);
                    }

                    let main_container = document.getElementById('modal-body-div');

                    while (main_container.hasChildNodes()) {
                        main_container.removeChild(main_container.childNodes[0]);
                    }

                    console.log(data);
                    for (let branch in data) {
                        if (branch != 'message' && branch != 'type') {

                            for (let exam in data[branch]) {

                                for (let date in data[branch][exam]) {

                                    let item = document.createElement("div");
                                    item.setAttribute("class", "item-schedule");

                                    let title = document.createElement("div");
                                    title.setAttribute("class", "title-schedule");
                                    title.innerHTML = "Branch: " + branch + "&nbsp;&nbsp;&nbsp;Exam:" + exam + "&nbsp;&nbsp;&nbsp;Date:" + date;
                                    item.appendChild(title);


                                    for (let time in data[branch][exam][date]) {
                                        for (let room in data[branch][exam][date][time]) {

                                            let room_div = document.createElement('div');
                                            room_div.setAttribute("class", "classroom-schedule");
                                            item.appendChild(room_div);

                                            let subtitle = document.createElement("div");
                                            subtitle.setAttribute("class", "subtitle-schedule");
                                            subtitle.innerHTML = "Location: " + room + "&nbsp;&nbsp;&nbsp;Subject:"+ data[branch][exam][date][time][room]['subject'] + "&nbsp;&nbsp;&nbsp;Time:" +time;
                                            room_div.appendChild(subtitle);

                                            let student_outer_div = document.createElement('div');
                                            student_outer_div.setAttribute("class", "row");
                                            room_div.appendChild(student_outer_div);
                                            {#console.log(data[branch][exam][date][time][room]);#}

                                            let roll_nos = data[branch][exam][date][time][room]['student'].sort();
                                            let table = document.createElement('table');
                                            let tr = document.createElement('tr');
                                            let td = document.createElement('td');
                                            let count = 0;
                                            for (let i in roll_nos) {
                                                if (count == 7) {
                                                    td.innerHTML += roll_nos[i] + "<br/>";
                                                    count = 0;
                                                } else {
                                                    td.innerHTML += roll_nos[i] + "&nbsp;&nbsp;";
                                                    count = count + 1;
                                                }
                                            }
                                            tr.appendChild(td);
                                            table.appendChild(tr);
                                            student_outer_div.appendChild(table);

                                        }
                                    }
                                    main_container.appendChild(item);
                                }
                            }
                        }
                    }
                    let text = document.getElementById('modal-footer');
                    while (text.firstChild) {
                        text.removeChild(text.firstChild);
                    }
                    let button = document.createElement('button');
                    button.innerHTML = "OK";
                    button.setAttribute("class", "btn btn-info");
                    button.setAttribute("data-dismiss", "modal");
                    text.appendChild(button);
                    $('#myModal').modal({
                        show: true,
                        closeOnEscape: true
                    });


                }
            });
        }
    </script>
{% endblock html %}

Exam/templates/view_schedule.html
{% extends 'dashboard_student.html' %}
{% block title %}
    Exam-Schedule | ERP
{% endblock title %}



{% block content %}

    <div id="exam_schedule" class="container-fluid"></div>

{% endblock content %}
{% block html %}
    <script>

    </script>
{% endblock html %}