Dashboard/urls.py
from django.conf.urls import url

from Dashboard import views

app_name = "dashboard"
urlpatterns = [

    # /dashboard/
    url(r'^$', views.show_dashboard, name='dashboard'),

    # /test_url/
    url(r'^test_url/$', views.test_url, name='test_url'),

    # /dashboard/logout
    url(r'^logout/$', views.logout_user, name="logout"),

    # /dashboard/profile/
    url(r'^profile/$', views.view_profile, name="profile"),

    url(r'^research/$', views.list_research, name="research"),

    url(r'^toggle_availability/$', views.toggle_availability, name='toggle_availability'),

    url(r'^get_subjects/$', views.get_subjects, name='get_subjects'),

    url(r'^android/get_subjects/$', views.android_get_subjects, name='android_get_subjects'),

    url(r'^set_substitute/(?P<key>[0-9]+)$', views.set_substitute, name='set_substitute'),

    url(r'^android/set_substitute/$', views.android_set_substitute, name='andriod_set_substitute'),

    url(r'^android/toggle_availability$', views.android_toggle_availability, name='android_toggle_availability'),

    url(r'^android/get_date$', views.get_date, name='get_date'),

    url(r'^get_notifications/$', views.get_notifications, name='get_notifications'),

    url(r'^android/get_notifications/$', views.android_get_notifications, name='android_get_notifications'),

    url(r'^show_all_notifications/$', views.show_all_notifications, name='show_all_notifications'),

    url(r'^show_all_notifications/(?P<page>[0-9]+)$', views.show_all_notifications, name='show_all_notifications'),

    url(r'^view_notification/$', views.view_notification, name='view_notification'),

    url(r'^read_all_notification/$', views.read_all_notification, name='read_all_notification'),

    url(r'^extra_lecture/$', views.take_extra_lecture, name='take_extra_lecture'),

    #setup/
    url(r'^setup/branch/$', views.setup_branch, name='setup_branch'),

    url(r'^setup/year/$', views.setup_year, name='setup_year'),

    url(r'^setup/division/$', views.setup_division, name='setup_division'),

    url(r'^setup/time/$', views.setup_time, name='setup_time'),

    url(r'^setup/semester/$', views.setup_semester, name='setup_semester'),

]

EnterpriseResourcePlanning/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

from EnterpriseResourcePlanning import views, settings

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^update/', include('Update.urls')),
    url(r'^register/', include('Registration.urls')),
    url(r'^attendance/', include('Attendance.urls')),
    # url(r'^administrator/', include('administrator.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^login/', include('Login.urls')),
    url(r'^dashboard/', include('Dashboard.urls')),
    url(r'^timetable/', include('Timetable.urls')),
    url(r'^request/', include('Requests.urls')),
    url(r'^report/', include('Report.urls')),
    url(r'^general/', include('General.urls')),
    url(r'^exam/', include('Exam.urls')),
    url(r'^backup/', include('BackupRestore.urls')),
    url(r'^internship/', include('Internship.urls')),
    url(r'^feedback/', include('Feedback.urls'))
    # url(r'^research/', include('Research.urls')),
    # url(r'^update/', include('Update.urls'))

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# urlpatterns += staticfiles_urlpatterns()

Exam/urls.py
from django.conf.urls import url

from Exam import views

app_name = "exam"
urlpatterns = [
    # /exam/add
    url(r'^add/$', views.exam_register, name='exam_register'),
    # /exam/detail
    url(r'^detail/$', views.exam_detail, name='exam_detail'),
    # /exam/get_subjects
    url(r'^get_subjects/$', views.get_subjects, name='get_subjects'),
    # /exam/view_exam
    url(r'^view_exam/$', views.view_exam, name='view_exam'),
    # /exam/manage_exam
    url(r'^manage_exam/$', views.manage_exam, name='manage_exam'),
    # /exam/set_rooms
    url(r'^set_rooms/$', views.set_rooms, name='set_rooms'),
    # /exam/ste_exam_time
    url(r'^set_exam_time/$', views.set_exam_time, name='set_exam_time'),
    # /exam/check_availability
    url(r'^check_availability/$', views.check_availability, name='check_availability'),
    # /exam/check_availability/exam_group
    url(r'^check_availability/(?P<still_schedule>[0-9]+)/$', views.check_availability, name='check_availability'),
    # /exam/android/types_of_exam/
    url(r'^android/types_of_exam/$', views.android_types_of_exam, name='android_types_of_exam'),
    # /exam/android/exam_subjects/
    url(r'^android/exam_subjects/$', views.android_subject_for_exam, name='android_subject_for_exam'),

]

Report/urls.py
from django.conf.urls import url, include

from . import views

app_name = 'report'

urlpatterns = [
    url(r'^student', views.student_details, name='student_details'),

    url(r'^faculty', views.faculty_details, name='faculty_details'),

    url(r'^get_excel/$', views.get_excel, name='get_excel'),

    url(r'^get_timetable/$', views.get_timetable, name='get_timetable'),

    url(r'^download_timetable_excel/$', views.download_excel_timetable, name='download_excel_timetable'),

    url(r'^excel_timetable/$', views.excel_timetable, name='excel_timetable'),

    url(r'^excel_room_schedule/$', views.excel_room_schedule, name='excel_room_schedule'),

    url(r'^download_excel_room_schedule/$', views.download_excel_room_schedule, name='download_excel_room_schedule'),

    url(r'^excel_attendance/$', views.excel_attendance, name='excel_attendance'),

    url(r'^download_excel_attendance_subject/$', views.download_excel_attendance_subject,
        name='download_excel_attendance_subject'),

]

Dashboard/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from General.models import Division, Batch
from Registration.models import Branch


class SpecificNotification(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    datetime = models.DateTimeField()
    notification = models.CharField(max_length=5000)
    heading = models.CharField(max_length=100)
    action = models.CharField(max_length=500,default='')
    type = models.CharField(max_length=200, null=True)
    is_active = models.BooleanField(default=True)
    priority = models.IntegerField(default=1)
    has_read = models.BooleanField(default=False)

    def __str__(self):
        str = self.heading
        if self.user.faculty:
            str += self.user.faculty.initials
        else:
            str += self.user.student.gr_number
        return str


class GeneralStudentNotification(models.Model):
    datetime = models.DateTimeField()
    notification = models.CharField(max_length=5000)
    heading = models.CharField(max_length=100)
    action = models.CharField(max_length=500, default='')
    type = models.CharField(max_length=200, null=True)
    priority = models.IntegerField(default=1)
    division = models.ForeignKey(Division, on_delete=models.CASCADE, null=True)
    batch = models.ForeignKey(Batch, null=True,blank=True,on_delete=models.CASCADE)
    for_batch = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.action


class GeneralFacultyNotification(models.Model):
    datetime = models.DateTimeField()
    notification = models.CharField(max_length=5000)
    heading = models.CharField(max_length=100)
    action = models.CharField(max_length=500, default='')
    type = models.CharField(max_length=200, null=True)
    priority = models.IntegerField(default=1)
    division = models.ForeignKey(Division, on_delete=models.CASCADE)
    branch = models.ForeignKey(Branch,on_delete=models.CASCADE)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.action

Dashboard/views.py
import json, copy
from collections import OrderedDict
from itertools import chain

import xlsxwriter
from django import urls
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core import serializers
from django.db.models import Q
from django.http import HttpResponseRedirect, HttpResponse, HttpResponseBadRequest, JsonResponse
from django.shortcuts import render, redirect
from django.utils import timezone
from django.utils.dateparse import parse_date
from django.views.decorators.csrf import csrf_exempt

from Attendance.models import StudentAttendance, StudentSubjectTotalAttendance, SubjectLecture
from Dashboard.models import SpecificNotification, GeneralStudentNotification, GeneralFacultyNotification
from EnterpriseResourcePlanning.settings import NOTIFICATION_LONG_LIMIT, NOTIFICATION_SMALL_LIMIT
from General.models import Batch, StudentDetail, Division, CollegeYear, FacultySubject, BranchSubject, YearBranch, \
    ElectiveDivision, Semester, YearSemester, Shift
from General.views import notify_users
from Registration.forms import StudentForm, FacultyForm
from Registration.models import Student, Branch, Faculty, ElectiveSubject, Subject
import datetime

# Student dashboard
from Registration.views import has_role
from Research.models import Paper
from Timetable.models import Timetable, DateTimetable, Time, Room
from Update.forms import StudentUpdateForm, FacultyUpdateForm
from Roles.models import RoleMaster, RoleManager


# def student(request):
#     user = request.user
#     # If user exists in session (i.e. logged in)
#     if not user.is_anonymous:
#         student_obj = user.student
#         form = StudentForm(instance=student_obj)
#         return render(request, 'dashboard.html', {
#             'form': form,
#             'first_name': user.first_name,
#             'last_name': user.last_name,
#
#         })
#     else:
#         return HttpResponseRedirect('/login/')


def logout_user(request):
    logout(request)
    return HttpResponseRedirect('/login/')


def show_dashboard(request):
    class_active = "dashboard"
    user = request.user
    # If user exists in session (i.e. logged in)
    if not user.is_anonymous:
        is_faculty = has_role(user, 'faculty')
        is_student = has_role(user, 'student')
        if is_student:
            student = user.student

            student_subject = StudentSubjectTotalAttendance.objects.filter(student=student)

            attendance = {}

            attended = 0
            total = 0

            for each in student_subject:
                division = StudentDetail.objects.get(student=student).batch.division
                faculty_subject = FacultySubject.objects.get(subject=each.subject, division=division)
                total_lectures = SubjectLecture.objects.get(faculty_subject=faculty_subject).conducted_lectures

                total += total_lectures
                attended += each.attended

                attendance[each.subject.short_form] = {
                    'total': total_lectures,
                    'attended': each.attended,
                    'attendance': round(100 * each.attended / total_lectures, 2) if total_lectures is not 0 else 0 + '%'
                }

            total_percent = round(100 * attended / total, 2) if total is not 0 else 0

            college_extra_detail = StudentDetail.objects.get(student=student, is_active=True).batch.division
            if request.method == "GET":
                timetable = sorted(
                    DateTimetable.objects.filter(date=datetime.date.today(), original__division=college_extra_detail,
                                                 is_active=True),
                    key=lambda x: (x.date, x.original.time.starting_time))

                return render(request, 'dashboard_student.html', {
                    'timetable': timetable,
                    'selected_date': datetime.date.today().strftime('%d-%m-%Y'),
                    'attendance': attendance,
                    'total_attendance': total_percent
                })
            else:
                if 'GO' in request.POST:
                    selected_date = datetime.datetime.strptime(request.POST.get('selected_date'), '%d-%m-%Y').date()
                    timetable = sorted(
                        DateTimetable.objects.filter(date=selected_date,
                                                     original__division=college_extra_detail, is_active=True),
                        key=lambda x: (x.date, x.original.time.starting_time))

                    return render(request, 'dashboard_student.html', {
                        'timetable': timetable,
                        'selected_date': selected_date.strftime('%d-%m-%Y'),
                        'attendance': attendance,
                        'total_attendance': total_percent
                    })

                elif request.POST.__contains__('previous') or request.POST.__contains__('next'):
                    selected_date = datetime.datetime.strptime(request.POST.get('selected_date'), '%d-%m-%Y').date()
                    if request.POST.get('previous'):
                        selected_date = selected_date + datetime.timedelta(-1)

                    if request.POST.get('next'):
                        selected_date = selected_date + datetime.timedelta(1)

                    timetable = sorted(
                        DateTimetable.objects.filter(date=selected_date,
                                                     original__division=college_extra_detail, is_active=True),
                        key=lambda x: (x.date, x.original.time.starting_time))

                    return render(request, 'dashboard_student.html', {
                        'timetable': timetable,
                        'selected_date': selected_date.strftime('%d-%m-%Y'),
                        'attendance': attendance,
                        'total_attendance': total_percent
                    })

        elif is_faculty:
            faculty = user.faculty

            if request.method == "GET":
                timetable = sorted(
                    DateTimetable.objects.filter(date=datetime.date.today(), original__faculty=faculty, is_active=True),
                    key=lambda x: (x.date, x.original.time.starting_time))
                return render(request, 'dashboard_faculty.html', {
                    'class_active': class_active,
                    'timetable': timetable,
                    'selected_date': datetime.date.today().strftime('%d-%m-%Y'),
                })

            else:
                if 'GO' in request.POST:
                    selected_date = datetime.datetime.strptime(request.POST.get('selected_date'), '%d-%m-%Y').date()
                    timetable = sorted(
                        DateTimetable.objects.filter(Q(date=selected_date), Q(is_active=True),
                                                     Q(original__faculty=faculty) | Q(substitute__faculty=faculty)),
                        key=lambda x: (x.date, x.original.time.starting_time))

                    return render(request, 'dashboard_faculty.html', {
                        'class_active': class_active,
                        'timetable': timetable,
                        'selected_date': selected_date.strftime('%d-%m-%Y'),
                    })

                elif request.POST.__contains__('previous') or request.POST.__contains__('next'):
                    selected_date = datetime.datetime.strptime(request.POST.get('selected_date'), '%d-%m-%Y').date()
                    if request.POST.get('previous'):
                        selected_date = selected_date + datetime.timedelta(-1)

                    if request.POST.get('next'):
                        selected_date = selected_date + datetime.timedelta(1)

                    timetable = sorted(
                        DateTimetable.objects.filter(Q(date=selected_date), Q(is_active=True),
                                                     Q(original__faculty=faculty) | Q(substitute__faculty=faculty)),
                        key=lambda x: (x.date, x.original.time.starting_time))

                    return render(request, 'dashboard_faculty.html', {
                        'class_active': class_active,
                        'timetable': timetable,
                        'selected_date': selected_date.strftime('%d-%m-%Y'),
                    })

                elif 'date_timetable' in request.POST:
                    selected_date = datetime.datetime.strptime(request.POST.get('selected_date'), '%d-%m-%Y').date()
                    timetable = sorted(
                        DateTimetable.objects.filter(Q(date=selected_date), Q(is_active=True),
                                                     Q(original__faculty=faculty) | Q(substitute__faculty=faculty)),
                        key=lambda x: (x.date, x.original.time.starting_time))

                    selected_class_obj = DateTimetable.objects.get(pk=request.POST.get('date_timetable'),
                                                                   is_active=True)

                    if selected_class_obj.original.is_practical:
                        attendance = StudentAttendance.objects.filter(
                            student__studentdetail__batch=selected_class_obj.original.batch,
                            student__studentdetail__is_active=True,
                            timetable=selected_class_obj)

                        present_roll = sorted(
                            [StudentDetail.objects.get(student=each.student, is_active=True).roll_number for each in
                             attendance if
                             each.attended is True])

                        all_students = StudentDetail.objects.filter(

Dashboard/templates/all_notifications.html
{% extends 'dashboard_faculty.html' %}
{% load humanize %}
{% block title %}
    All Notifications | ERP
{% endblock title %}

{% block extra_style %}
    <style>
        .notification_overlay_text h2 {
            color: white !important;
        }

        .table-responsive {
            overflow: hidden;
        }

        .white-text {
            color: white !important;
        }
    </style>

{% endblock extra_style %}


{% block content %}
    <legend>All Notifications</legend>
    <div class="row">
        <button class="btn" onclick="readNotification();">Mark all as read</button>
        <div class="table-responsive">
            <table class="table table-hover white" id="notification_table">
                {% for each in notifications %}
                    {% if each.has_read is False %}
                        <tr class="info" id="{{ each.pk }}"
                            onclick="this.classList.remove('info'); this.classList.add('active'); expandNotification('{{ each.pk }}')"
                            data-target="#myModal" data-toggle="modal">
                            <td>{{ each.datetime |naturaltime }}</td>
                            <td>
                                {{ each.heading }}<br/>
                                {{ each.notification }}
                            </td>
                        </tr>{% else %}
                        <tr class="active" id="{{ each.pk }}" onclick="expandNotification('{{ each.pk }}')"
                            data-target="#myModal" data-toggle="modal">
                            <td>{{ each.datetime |naturaltime }}</td>
                            <td>
                                <div class="row">{{ each.heading }}</div>
                                <div class="row">{{ each.notification }}</div>
                            </td>
                        </tr>
                    {% endif %}

                {% endfor %}
            </table>
        </div>
    </div>
    <div class="row" align="center">
        <form action="{% url 'dashboard:show_all_notifications' %}" method="get">
            <ul class="pagination">
                <li><a href="#">&laquo;</a></li>
                {% for page in pages %}
                    {% if page == current_page %}
                        <li class="active"><a href="{% url 'dashboard:show_all_notifications' page %}">{{ page }}</a>
                        </li>
                    {% else %}
                        <li><a href="{% url 'dashboard:show_all_notifications' page %}">{{ page }}</a></li>
                    {% endif %}
                {% endfor %}
                <li><a href="#">&raquo;</a></li>
            </ul>
        </form>
    </div>


    <script>

        var json_notifications;
        var notification_model = {{ notification_model | safe }};

        function expandNotification(pk) {
            $.ajax({
                url: '{% url 'dashboard:view_notification' %}',
                type: 'POST',
                data: {
                    'csrfmiddlewaretoken': '{{ csrf_token }}',
                    'pk': pk,
                    'model': notification_model[pk],

                },
                success: function (data) {
                    json_notifications = JSON.parse(data);
                    temp_json = json_notifications;

                    let modalTitle = document.getElementById("modal-title");
                    let modalBodyText = document.getElementById("modal-body-text");
                    let modalBodyDiv = document.getElementById("modal-body-div");

                    while(modalBodyDiv.hasChildNodes()) {
                        modalBodyDiv.removeChild(modalBodyDiv.childNodes[0]);
                    }

                    modalTitle.innerHTML = json_notifications["fields"]["heading"];
                    modalBodyText.innerText = json_notifications["fields"]["notification"];


                    let text = document.getElementById('modal-footer');
                    while (text.firstChild) {
                        text.removeChild(text.firstChild);
                    }

                    var split_action = json_notifications['fields']['action'].split('/');
                    var id = split_action[split_action.length - 1];

                    if (json_notifications["fields"]["type"] === "Decision") {
                        let button = document.createElement('button');
                        button.innerHTML = "YES";
                        button.setAttribute("class", "btn btn-success");
                        button.style.marginRight = "5%";
                        button.setAttribute("onclick", "setSubstitute('" + json_notifications['fields']['action'] + "')");
                        button.setAttribute("onclick", "getSubjects(" + id + ")");
                        text.appendChild(button);
                        button = document.createElement('button');
                        button.innerHTML = "NO";
                        button.setAttribute("class", "btn btn-danger");
                        button.setAttribute("data-dismiss", "modal");
                        text.appendChild(button);
                    } else if (temp_json["fields"]["type"] === "forward") {
                        let a = document.createElement('a');
                        a.innerHTML = "Go To Subject Registration";
                        a.setAttribute("class", "btn btn-success");
                        a.setAttribute("href", json_notifications["fields"]["action"]);
                        text.appendChild(a);
                    } else {

                        let button = document.createElement('button');
                        button.innerHTML = "OK";
                        button.setAttribute("class", "btn btn-info");
                        button.setAttribute("data-dismiss", "modal");
                        text.appendChild(button);
                    }

                    {#document.getElementById("notification_overlay").style.display = "block";#}
                }

            });
        }

        function overlay_off() {
            document.getElementById("notification_overlay").style.display = "none";
        }


        function readNotification() {
            var pk_list = [];
            $('#notification_table tr[class="info"]').each(function () {
                pk_list.push(this.id);
                this.classList.remove('info');
                this.classList.add('active');
            });
            if (pk_list.length > 0) {
                $.ajax({
                    url: '{% url 'dashboard:read_all_notification' %}',
                    type: "POST",
                    data: {
                        'csrfmiddlewaretoken': '{{ csrf_token }}',
                        'pk': JSON.stringify(pk_list)
                    },
                    success: function () {
                    }
                });
            }
        }
    </script>
{% endblock content %}

Dashboard/templates/get_excel.html
{% extends 'dashboard_faculty.html' %}
{% block title %}
    ERP| Excel
{% endblock title %}


{% block content %}



{% endblock content %}

Dashboard/templates/setup_division.html
{% extends "./dashboard_faculty.html" %}

{% block title %}Getting Started | ERP {% endblock title %}


{% block content %}

    <div class="col-md-4">
        <div class="row">
            <a class="btn btn-default btn-circle" href="{% url 'dashboard:setup_semester' %}"><i
                    class="glyphicon glyphicon-chevron-left"></i></a>
            <a class="btn btn-link" href="{% url 'dashboard:setup_semester' %}">Previous Step: Semester Details</a>


        </div>
        <div class="row" id="divisions_registered">

        </div>
    </div>

    <div class="col-md-4">
        <form method="post" action="{% url 'dashboard:setup_division' %}" id="division_form">
            {% csrf_token %}
            <legend>Register new division</legend>
            <div class="form-element">
                <label for="branch">Branch</label>
                <select class="form-control" id="branch" name="branch" onchange="loadYear()" required></select>
            </div>
            <div class="form-element">
                <label for="year">Year</label>
                <select class="form-control" id="year" name="year" onchange="showDivisionRegistered()" onload="showDivisionRegistered()" required></select>
            </div>
            <div class="form-element">
                <label for="number_of_division">Number of division</label>
                <input type="text" class="form-control" id="number_of_division" required>
            </div>
            <div class="form-element">
                <input type="button" class="btn btn-primary" value="GO" onclick="showDivisionNameInput()">
            </div>
            <div class="form-element" id="division_names">

            </div>
        </form>
    </div>
    <div class="col-md-3 col-md-offset-1">
        <div class="row">

            <a class="btn btn-link" href="{% url 'dashboard:setup_time' %}">Next Step: Time Registration</a>

            <a class="btn btn-success btn-circle" href="{% url 'dashboard:setup_time' %}"><i
                    class="glyphicon glyphicon-chevron-right"></i></a>
        </div>
    </div>
{% endblock content %}

{% block on_ready %}
    loadBranch();
{% endblock on_ready %}

{% block html %}
    <script>

        var data = {{ data|safe }};

        function loadBranch() {
            let branch_combo = document.getElementById('branch');
            for (let branch in data) {
                let option = document.createElement('option');
                option.text = branch;
                option.value = branch;
                branch_combo.appendChild(option);
            }
            loadYear();
        }

        function loadYear() {
            let selected_branch = document.getElementById('branch').value;
            let year_combo = document.getElementById('year');

            while (year_combo.hasChildNodes()) {
                year_combo.removeChild(year_combo.childNodes[0]);
            }

            for (let year in data[selected_branch]) {
                let option = document.createElement('option');
                option.text = year;
                option.value = [year];
                year_combo.appendChild(option);
            }
            showDivisionRegistered();
        }

        function showDivisionNameInput() {
            let number_of_division = document.getElementById('number_of_division').value;
            let selected_branch = document.getElementById('branch').value;
            let selected_year = document.getElementById('year').value;
            let division_div = document.getElementById('division_names');

            while (division_div.hasChildNodes()) {
                division_div.removeChild(division_div.childNodes[0]);
            }

            division_div.appendChild(document.createTextNode('Enter division name and select shift'));

            for (let i = 0; i < number_of_division; i++) {
                let div = document.createElement('div');
                div.setAttribute('class', 'form-element');


                let input = document.createElement('input');
                input.setAttribute('type', 'text');
                input.setAttribute('autocomplete', 'off');
                input.setAttribute('required', 'true');
                input.setAttribute('class', 'form-control division-name');
                input.setAttribute('name', 'division');
                input.setAttribute('maxlength', '1');
                div.appendChild(input);

                let select = document.createElement('select');
                select.setAttribute('name', 'shift');
                select.setAttribute('required', 'true');
                select.setAttribute('class', 'form-control division-name');

                for (let i = 1; i <= data[selected_branch][selected_year]['shift']; i++) {
                    let option = document.createElement('option');
                    option.text = i;
                    option.value = i;
                    select.appendChild(option);
                }
                div.appendChild(select);
                division_div.appendChild(div);
            }

            let button = document.createElement('input');
            button.setAttribute('type', 'submit');
            button.setAttribute('class', 'btn btn-primary');
            button.setAttribute('value', 'Submit');
            division_div.appendChild(button);
        }

        function showDivisionRegistered() {
            let selected_branch = document.getElementById('branch').value;
            let selected_year = document.getElementById('year').value;

            let div_to_append = document.getElementById('divisions_registered');

            while (div_to_append.hasChildNodes()) {
                div_to_append.removeChild(div_to_append.childNodes[0]);
            }


            let label = document.createElement('label');
            label.innerHTML = "Registered divisions for " + selected_branch + "-" + selected_year;
            div_to_append.appendChild(label);

            for (let i in data[selected_branch][selected_year]['division']) {
                let p = document.createElement('p');
                p.innerHTML = data[selected_branch][selected_year]['division'][i];
                div_to_append.appendChild(p);
            }

        }

    </script>

{% endblock html %}